name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bot-image

    - name: Deploy
      runs:
        using: 'docker'
        image: 'Dockerfile'
        args: -e TOKEN ${{ secrets.TOKEN }}
